### ISSUE TITLE
Add documentation for O365_ACTUALLY_SEND_IN_DEBUG setting

### ISSUE THREAD

**Issue by lucasmoeskops** [evyd13/django-o365mail#3]
Hi,

Thanks for this package! Just what I needed. It is well documented but it might be useful to also document the O365_ACTUALLY_SEND_IN_DEBUG setting which was preventing mail from being sent for me locally.

**Comment by evyd13** [comment]
Done, thanks!

**Comment by vanderzielj** [comment]
Information for those (perhaps only new to Django) who would like to send an email during testing - the flag "O365_ACTUALLY_SEND_IN_DEBUG" is not the flag you are looking for!

You will need to override the default Django test behavior that replaces the real email back end with a dummy one by annotating your test class(es) or method(s) with: `@override_settings(EMAIL_BACKEND="django_o365mail.EmailBackend")`
