### ISSUE TITLE
How to get the following id secret and tanant

### ISSUE THREAD

**Issue by technqvi** [evyd13/django-o365mail#7]
Hi.

Once I installed it package successfully how I get
can the following information from office365  to configure in settings.py?

O365_MAIL_CLIENT_ID = 'REPLACE THIS'
O365_MAIL_CLIENT_SECRET = 'REPLACE THIS'
O365_MAIL_TENANT_ID = 'REPLACE THIS'
 You can refer to link to  how to generate these information?

**Comment by dejaeghered** [comment]
https://o365.github.io/python-o365/latest/getting_started.html
The OAuth Setup (Pre Requisite) section is what can help you

**Comment by technqvi** [comment]
Thank you
